In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df
#df se usa para imprimir la base de datos

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [5]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

Filtro 1: mostrar los datos del vendedor Leticia Ramirez

In [4]:
#filtro por objeto
filtro1=df[(df["NOMBRE_VENDEDOR"] == "LETICIA RAMIREZ HERNANDEZ")]
filtro1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49

crear su .csv

In [5]:
filtro1.to_csv("Enrtegable1.csv")

Filtro 2: mostrar filas no consecutivas

In [6]:
#filtro por filas no consecutivas 
filtro2= df.iloc[ [2,5], : ]       
filtro2

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32

se crea su .csv

In [7]:
filtro2.to_csv("Enrtegable2.csv")

Filtro 3: imprimir columnas consecutivas

In [8]:
#filtro por columnas
filtro3= df.iloc[ : ,1:3]
filtro3

      FECHA_DOC            NOMBRE_VENDEDOR
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ
2    2022-01-05   DIEGO ARMANDO LEON DURAN
3    2022-01-05   DIEGO ARMANDO LEON DURAN
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ
...         ...                        ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1425 2022-12-23         AARON NUÑO CORDOVA

[1426 rows x 2 columns]

se crea su .csv

In [9]:
filtro3.to_csv("Enrtegable3.csv")

Filtro 4: imprimir filas y columnas específicas

In [11]:
#Aplicaremos Filtro de filas vs. columnas
filtro4 = df.loc[:,["NOMBRE_VENDEDOR","NOMBRE_CLIENTE","CANT"]]
filtro4

                NOMBRE_VENDEDOR                NOMBRE_CLIENTE  CANT
0     LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL     1
1     LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE     1
2      DIEGO ARMANDO LEON DURAN     ANA BARBARA CRUZ PALACIOS     7
3      DIEGO ARMANDO LEON DURAN          OMAR RODRIGUEZ GOMEZ     1
4     LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL     2
...                         ...                           ...   ...
1421  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ     6
1422  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ     6
1423  LETICIA RAMIREZ HERNANDEZ          SEVEN DAYS ALL SPORT     3
1424  LETICIA RAMIREZ HERNANDEZ           REVUELTA MONTECARLO     1
1425         AARON NUÑO CORDOVA                CPEG SOLUTIONS    10

[1426 rows x 3 columns]

se crea su .csv

In [12]:
filtro4.to_csv("Filtro4.csv")

Filtro 5: imprime los primeros n registros de la BD

In [23]:
#filtro por cabecera
filtro5=df.head()
filtro5

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

se crea el .csv

In [24]:
filtro5.to_csv("Entregable5.csv")

Filtro 6: imprime los últimos n registros de la BD

In [25]:
#filtro por cola
filtro6=df.tail()
filtro6

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

se crea el .csv

In [26]:
filtro6.to_csv("Entregable6.csv")

Filtro 7: MARGEN_TOTAL_CALCULADO menores a 260

In [29]:
#Filtro por comparación
filtro7 = df[df["MARGEN_TOTAL_CALCULADO"] < 260]
filtro7

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
15,F37058,2022-01-05,DIEGO ARMANDO LEON DURAN,MOLINERA DE MEXICO,5,PT00070,"PT-100 1/8""ØX30MM EXT 1.5MT 3HILOS Z/ESP",192.50,51.73,149.60,481.25,397.08,42.90,84.17
17,F37060,2022-01-05,DIEGO ARMANDO LEON DURAN,OSCAR VALDEZ GUADARRAMA,3,PJ31C1F1AA00,"TER J 3/16""ØX2"" EXT.2MT CON-1/2"" NPT",125.00,0.00,141.90,375.00,425.69,-16.90,-50.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,F39608,2022-11-18,LETICIA RAMIREZ HERNANDEZ,ENPLA,2,TP0002,TERMOPAR J3/16 Ø X 1' 1/2 EXT. 1.5 MT,155.00,63.31,63.31,310.00,126.62,91.69,183.38
1307,F39608,2022-11-18,LETICIA RAMIREZ HERNANDEZ,ENPLA,1,TP0003,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2 MT,190.00,65.16,65.16,190.00,65.16,124.84,124.84
1319,F39621,2022-11-24,LETICIA RAMIREZ HERNANDEZ,PISTIS,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,125.00,48.20,48.20,125.00,48.20,76.80,76.80
1353,F39687,2022-12-05,LETICIA RAMIREZ HERNANDEZ,JOCAR ELECTRICA DEL CENTRO,3,TP0003,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2 MT,155.00,79.01,79.01,465.00,237.03,75.99,227.97
1364,F39730,2022-12-08,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TP0012,"TERMOPAR CERAMICO T/ K"" LONG 12"" CAL.14""",315.00,57.60,57.60,315.00,57.60,257.40,257.40

se crea el .csv

In [30]:
filtro7.to_csv("Entregable7.csv")

Filtro 8: se muestra PRECIO_UNITARIO < 300 y el NOMBRE_VENDEDOR == "LETICIA"

In [14]:
#filtro Y
filtro8 = df[(df["PRECIO_UNITARIO"] < 300) & (df["NOMBRE_VENDEDOR"] == "LETICIA RAMIREZ HERNANDEZ")]
filtro8

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
89,F37193,2022-01-26,LETICIA RAMIREZ HERNANDEZ,BESSER VACUUM AMERICA,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,98.00,38.96,38.96,98.00,38.96,59.04,59.04
93,F37214,2022-01-27,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,107.76,38.96,38.96,107.76,38.96,68.80,68.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,F39608,2022-11-18,LETICIA RAMIREZ HERNANDEZ,ENPLA,2,TP0002,TERMOPAR J3/16 Ø X 1' 1/2 EXT. 1.5 MT,155.00,63.31,63.31,310.00,126.62,91.69,183.38
1307,F39608,2022-11-18,LETICIA RAMIREZ HERNANDEZ,ENPLA,1,TP0003,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2 MT,190.00,65.16,65.16,190.00,65.16,124.84,124.84
1319,F39621,2022-11-24,LETICIA RAMIREZ HERNANDEZ,PISTIS,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,125.00,48.20,48.20,125.00,48.20,76.80,76.80
1330,F39636,2022-11-25,LETICIA RAMIREZ HERNANDEZ,TERMOFORMATEC,10,TP0003,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2 MT,195.00,0.00,88.63,1950.00,886.28,106.37,1063.72
1353,F39687,2022-12-05,LETICIA RAMIREZ HERNANDEZ,JOCAR ELECTRICA DEL CENTRO,3,TP0003,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2 MT,155.00,79.01,79.01,465.00,237.03,75.99,227.97

se crea su .csv

In [20]:
filtro8.to_csv("Entregable8.csv")

Filtro 9: se muestra "SUBTOTAL_PARTIDA" > 500 o "FECHA_DOC" que sea igual a "2022-12-23"

In [16]:
filtro9 = df[(df['SUBTOTAL_PARTIDA'] > 500) | (df['FECHA_DOC'] == "2022-12-23")]
filtro9

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

se crea su .csv

In [18]:
filtro9.to_csv("Entregale9.csv")

Filtro 10: imprimir usando el operador NOT

In [6]:
filtro10 = df[~(df["FECHA_DOC"] == "2022-01-05")]
filtro10

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
21,F37067,2022-01-07,DIEGO ARMANDO LEON DURAN,APEX TOOL GROUP MANUFACTURING MEXICO,3,MR01934,"PT-100 3/16""ØX11/2"" EXT3MTS TEFLON Z-PIN",938.53,147.76,147.76,2815.59,443.27,790.77,2372.32
22,F37068,2022-01-07,DIEGO ARMANDO LEON DURAN,KWANTREATS,1,PT00080,PT-100 4MMØX10CM EXT 5MT TEFLON 2HILOS,718.52,259.35,259.35,718.52,259.35,459.17,459.17
23,F37068,2022-01-07,DIEGO ARMANDO LEON DURAN,KWANTREATS,1,PT00081,"PT-100 DE 1/4""ØX14.5CM EXT 5MT CONECTOR",898.25,332.65,332.65,898.25,332.65,565.60,565.60
24,F37069,2022-01-07,AARON NUÑO CORDOVA,ADVANEX DE MEXICO,2,RP00150,REPARACION DE TERMOPAR,1500.00,0.36,0.36,3000.00,0.72,1499.64,2999.28
25,F37071,2022-01-07,DIEGO ARMANDO LEON DURAN,FRANCISCO JAVIER MEDINA SANCHEZ,3,TUA00009,"TUB INOX 7/16""ØX510MM ""U""8000W 440V TAP",1848.00,1081.89,1081.89,5544.00,3245.66,766.11,2298.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

se crea su .csv

In [21]:
filtro10.to_csv("Entregable10.csv")